library(enerscape)
library(terra)
i <- as.numeric(readLines("C:\\Users\\amtom\\Desktop\\global_variable.txt"))
data("sirente")
folder_path <- paste0("C:/Users/amtom/Desktop/Folder_", i)
dir.create(folder_path)
dem <- rast(sirente, crs = "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs",extent = ext(879340, 885280, 4672880, 4676810))
w <- dem
png_file_1 <- paste0(folder_path,"/dem_",i,".png")
png(png_file_1)
plot(dem)
dev.off()
cat("Digital Elevation Model saved as PNG:", png_file_1, "\n")
mass_string = readline(prompt = "Enter the mass of animal: ")
mass = as.integer(mass_string)
en <- enerscape(dem, mass, neigh = 4, unit = "kcal")
en_log <- log(en)
png_file_2 <- paste0(folder_path,"/en_",i,".png")
png(png_file_2)
plot(en_log)
terra::contour(dem, add = TRUE, nlevels = 5)
dev.off()
en_log <- crop(en_log, ext(881306, 882853, 4674928, 4675984))
png_file_3 <- paste0(folder_path,"/en_crop_",i,".png")
png(png_file_3)
plot(en_log)
terra::contour(dem, add = TRUE, nlevels = 20)
dev.off()
radius_string = readline(prompt = "Enter the radius of analysis: ")
radius <- as.integer(radius_string)
omniscape_skeleton(en, path = folder_path, radius = radius)